
export const TRIVIA_STATE = 'TRIVIA_STATE'
export const TRIVIA_STATE_LOADING = 'TRIVIA_STATE_LOADING'
export const TRIVIA_STATE_ERROR = 'TRIVIA_STATE_ERROR'

export type triviaType = 'TRIVIA_STATE' | 'TRIVIA_STATE_ERROR' | 'TRIVIA_STATE_LOADING'